# Site settings
title: Cosechando Felicidad Inc.
email: info@harvestinghappiness.org
description: >
  Cosechando Felicidad, (or Harvesting Happiness in English), is a non-profit corporation 
  working in Santa Maria de Jesús, Guatemala. Our goal is to empower the 
  community by forming genuine relationships through which people can receive 
  the help they need.
footertext: Cosechando Felicidad Inc. is a 501(c)3 nonprofit working in Guatemala
baseurl: ""
url: "https://harvestinghappiness.org"
facebook_username: harvestinghappinessguate
instagram_username: harvestinghappinessguate

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
excerpt_separator: <!--endexcerpt-->

# Collection settings
collections:
  products:
    output: true
    permalink: /shop/:collection/:name/ 
defaults:
  - scope:
      path: ""
      type: "product"
    values:
      layout: "product"

newsletter: https://docs.google.com/forms/d/1UxdIzdVGaljOddK3Huq8BP0SYxs4xSLq1PQnSsLNZ7g/viewform
contactform: http://goo.gl/forms/iU8Y3sQoaN

plugins:
  - jekyll-sitemap