# Site settings
title: Cosechando Felicidad Inc.
email: emily@harvestinghappiness.org
description: > # this means to ignore newlines until "baseurl:"
  Cosechando Felicidad, (or Harvesting Happiness in English), is a non-profit corporation 
  working in Santa Maria de Jesús, Guatemala. Our goal is to empower the 
  community by forming genuine relationships through which people can receive 
  the help they need.
footertext: Cosechando Felicidad Inc. is a 501(c)3 nonprofit working in Guatemala
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://harvestinghappiness.org" # the base hostname & protocol for your site
facebook_username: harvestinghappinessguate
twitter_username:

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
excerpt_separator: <!--endexcerpt-->

newsletter: https://docs.google.com/forms/d/1UxdIzdVGaljOddK3Huq8BP0SYxs4xSLq1PQnSsLNZ7g/viewform
contactform: http://goo.gl/forms/iU8Y3sQoaN

gems:
  - jekyll-feed
