# Site settings
title: Harvesting Happiness
email: info@harvestinghappiness.org
description: > # this means to ignore newlines until "baseurl:"
  Cosechando Felicidad, Harvesting Happiness, is a non-profit corporation 
  working in Santa Maria de Jesús, Guatemala. Our goal is to empower the 
  community by forming genuine relationships through which people can receive 
  the help they need.
footertext: Harvesting Happiness is a 501(c)3 nonprofit working in Guatemala
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://harvestinghappiness.org" # the base hostname & protocol for your site
facebook_username: harvestinghappinessguate
twitter_username:

# Build settings
markdown: kramdown
highlighter: pygments
encoding: utf-8

newsletter: https://docs.google.com/forms/d/1UxdIzdVGaljOddK3Huq8BP0SYxs4xSLq1PQnSsLNZ7g/viewform
contactform: http://goo.gl/forms/iU8Y3sQoaN
