bag:
  id: 1
  name: Rectangular Crossbody Bag – Multicolored 
  summary: Handcrafted Guatemalan multicolored crossbody bag  
  description: Handcrafted Guatemalan bag. This bag is lined and features two zippered pockets and an adjustable leather strap. All bags are handmade, unique, and provide sustainable employment opportunities to the most vulnerable families in Santa María de Jesús, Guatemala and the surrounding areas. These bags are multicolored and each one is unique. 
               <br>All of our products provide meals for the elderly and support all our programs at Cosechando Felicidad Inc. 
  img: 1.jpg
  price: 20
  meals: 27
  categories: clothing, accessories
  options:
 (The only option is multicolored. Don’t know if there can either be a comment section here or later on in the order process where they can select what color predominates? It was super hard to sort them out into similar colors because they have a ton of colors in each.)
  inventory: 19 bags 

bag:
  id: 1
  name: Rectangular Crossbody Bag – Flower Print 
  summary: Handcrafted Guatemalan floral patterned crossbody bag  
  description: Handcrafted Guatemalan bag. This bag is lined and features two zippered pockets and an adjustable leather strap. All bags are handmade, unique, and provide sustainable employment opportunities to the most vulnerable families in Santa María de Jesús, Guatemala and the surrounding areas. Please choose the dominant color of your bag and be aware that all of our bags are handmade and unique.
               <br>All of our products provide meals for the elderly and support all our programs at Cosechando Felicidad Inc. 
  img: 1.jpg
  price: 50
  meals: 27
  categories: clothing, accesories
  options: (inventory numbers are in parenthesis)
    Tan (4)    
    Brown (3)
    Red (9)
    Blue (4)

Notebook:
  id: 1
  name: Multicolored Guatemalan Closeable Notebook with Pen
  summary: Beautiful multicolored typical notebook sleeve with replaceable notebook. Features closure and pen. 
  description: Handcrafted notebook made from typical Guatemalan fabric. Great for any occasion or gift! Serves as a reusable sleeve and inner notebook can be removed and replaced by another notebook or personal planner. Features closure and pen/pen holder. All items are handmade, unique, and provide sustainable employment opportunities to the most vulnerable families in Santa María de Jesús, Guatemala and the surrounding areas. Please choose the dominant color of your notebook and be aware that all of our notebooks are handmade and unique. 
               <br>All of our products provide meals for the elderly and support all our programs at Cosechando Felicidad Inc. 
  img: 1.jpg
  price: 8
  meals: 9
  categories: 
  options:
    Blue (18)
    Green (10)
    Yellow (4)
    Orange (7)
    Red (20)
    Brown  (17)
    Black (10)
    Pink (14)
    Purple (9)


bag:
  id: 1
  name: Cosmetic Crossbody Bag  or Wristlet 
  summary: Handcrafted Guatemalan cosmetic crossbody bag  or wristlet 
  description: Handcrafted Guatemalan bag. This bag is lined, features a zippered closure, and an optional leather strap. Can be used as a wristlet purse or a crossbody bag with the use of the included leather strap. Would make a great purse or even a makeup bag. All bags are handmade, unique, and provide sustainable employment opportunities to the most vulnerable families in Santa María de Jesús, Guatemala and the surrounding areas. Please choose the dominant color of your bag and be aware that all of our bags are handmade and unique.
               <br>All of our products provide meals for the elderly and support all our programs at Cosechando Felicidad Inc. 
  img: 1.jpg
  price: 15
Meals provided: 20
  categories: clothing, accessories
  options: (inventory numbers are in parenthesis)
    Pink (3)
    Multicolored (3)
    Black (2)
    Tan (4)
    Red (7)
    Brown (4)
    Blue (4)

Bracelet:
  id: 1
  name: Inspirational Handmade Bracelet  
  summary: Inspirational handmade Guatemalan adjustable bracelet  
  description: Handcrafted Guatemalan bracelet. Bracelet is made of resistant waxed cord and features adjustable closure in the back. These bracelets provide a source of income for single mothers and recovering victims of domestic and sexual abuse in Santa María de Jesús, Guatemala. Bracelets either say “La Vida Es Bella” which means “Life is Beautiful” or “Vivir es Incredible” which means “To Live is Incredible”. Each bracelet is handmade is one of a kind. Each bracelet is packaged in a handmade typical pouch. 
               <br>All of our products additionally provide meals for the elderly and support all our programs at Cosechando Felicidad Inc. 
  img: 1.jpg
  price: 5
  meals: 7
  categories: clothing, accessories, Jewelry
  options: No options 
  Inventory: 50 

Bracelet:
  id: 1
  name: Handmade Charm Bracelet  
  summary: Handmade Guatemalan adjustable charm bracelet  
  description: Handcrafted Guatemalan bracelet. Bracelet is made of resistant waxed cord and features adjustable closure in the back. These bracelets provide a source of income for single mothers and recovering victims of domestic and sexual abuse in Santa María de Jesús, Guatemala. Bracelets feature a charm such as the infinity sign, a leaf, hearts, etc. Each charm bracelet is handmade is one of a kind. Each bracelet is packaged in a handmade typical pouch.
               <br>All of our products additionally provide meals for the elderly and support all our programs at Cosechando Felicidad Inc. 
  img: 1.jpg
  price: 5
  meals: 7
  categories: clothing, accessories, Jewelry
  options: No options
  Inventory: 15 


Coin Purse:
  id: 1
  name: Handmade Multicolored Coin Purse   
  summary: Handmade Guatemalan coin purse 
  description: Handcrafted Guatemalan coin purse. This pouch is lined and features a zippered closure. Great for use as a small wallet, storing small loose items, or storing cards. Also great for storing loyalty or business cards. All bags are handmade, unique, and provide sustainable employment opportunities to the most vulnerable families in Santa María de Jesús, Guatemala and the surrounding areas. Please be advised that all bags are multicolored, handmade, and unique. 
               <br>All of our products provide meals for the elderly and support all our programs at Cosechando Felicidad Inc. 
  img: 1.jpg
  price: 5
  meals: 8
  categories: clothing, accessories 
  options: No options
  Inventory: 68


Keychain:
  id: 1
  name: Handmade Keychain from Recycled Plastic   
  summary: Renewable handmade Guatemalan keychain from recycled plastic   
  description: Renewable handmade Guatemalan keychain from recycled plastic. Features sturdy, painted, plastic beads. These keychains provide a source of income for single mothers and recovering victims of domestic and sexual abuse in Santa María de Jesús, Guatemala. Keychains are handmade and one of a kind. Each keychain is packaged in a handmade typical pouch.
               <br>All of our products additionally provide meals for the elderly and support all our programs at Cosechando Felicidad Inc. 
  img: 1.jpg
  price: 5
  meals: 8
  categories: clothing, accessories,
  options: 
    Blue (3)
    Pink (3)


Lanyard:
  id: 1
  name: Handmade Guatemalan Lanyard    
  summary: Handmade Guatemalan lanyard  
  description: Handcrafted Guatemalan Lanyard. This lanyard features a swivel and clip at the bottom. Great for use with keys, ID cards, at work, in hospitals, etc. All items are handmade, unique, and provide sustainable employment opportunities to the most vulnerable families in Santa María de Jesús, Guatemala and the surrounding areas. 
               <br>All of our products provide meals for the elderly and support all our programs at Cosechando Felicidad Inc. 
  img: 1.jpg
  price: 5
  meals: 9
  categories: clothing, accessories 
  options: 
    Pink (6)
    Red  (16)
    Blue  (7)
    Black (10)
    Cream (14)
    Multicolored (47)


Tote Bag:
  id: 1
  name: Handmade Tote Bag with Outer Pocket    
  summary: Handmade tote bag with outer pocket made from recycled materials   
  description: Handmade tote bag with outer pocket made from recycled fabric. Lined bag with large outside velcro-closing pocket.  These tote bags are made from recycled traditional skirts called “cortes” that are bought locally from families in need. The bags are then sewn by another family in need in Santa María de Jesús, Guatemala. All bags are handmade and one of a kind. 
               <br>All of our products additionally provide meals for the elderly and support all our programs at Cosechando Felicidad Inc. 
               <br>*Please note: the orange bag does not have an external pocket 
  img: 1.jpg
  price: 12
  meals: 12
  categories: clothing, accessories,
  options: 
    Black Shiny (2)
    Purple/Blue (6) 
    Rainbow (8)
    Turquoise (3)
    Orange w/o pocket (1)
    Navy (7)
    Pink/Purple Stripe (2)
    Black Matte (7)
    Green (8)
